PhotoSharingApplication/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;

namespace PhotoSharingApplication.Models
{
    public class Comment
    {
        public int CommentID { get; set; }

        public int PhotoID { get; set; }

        public string UserName { get; set; }

        public string Subject { get; set; }

        [DataType(DataType.MultilineText)]
        public string Body { get; set; }

        public virtual Photo Photo { get; set; }
    }
}

PhotoSharingApplication/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PhotoSharingApplication.Models
{
    public class Photo
    {
        public int PhotoID { get; set; }

        public string Title { get; set; }

        [DisplayName("Picture")]
        public byte[] PhotoFile { get; set; }

        public string ImageMimeType { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayName("Created Date")]
        [DisplayFormat(DataFormatString = "{0:MM / dd / yy}")]
        public DateTime CreatedDate{ get; set; }

        public string UserName { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
}
}

PhotoSharingApplication/Models/PhotoSharingContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Data.Entity;

namespace PhotoSharingApplication.Models
{
    public class PhotoSharingContext:DbContext
    {
        public PhotoSharingContext() : base("KeyDB") { }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<Comment> Comments { get; set; }
    }
}

PhotoSharingApplication/Models/PhotoSharingInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Data.Entity;
using System.IO;

namespace PhotoSharingApplication.Models
{
    public class PhotoSharingInitializer : DropCreateDatabaseAlways<PhotoSharingContext>
    {
        //This gets a byte array for a file at the path specified
        //The path is relative to the route of the web site
        //It is used to seed images
        private byte[] getFileBytes(string path)
        {
            FileStream fileOnDisk = new FileStream(HttpRuntime.AppDomainAppPath + path, FileMode.Open);
            byte[] fileBytes;
            using (BinaryReader br = new BinaryReader(fileOnDisk))
            {
                fileBytes = br.ReadBytes((int)fileOnDisk.Length);
            }
            return fileBytes;
        }

        protected override void Seed(PhotoSharingContext context)
        {
            var photos = new List<Photo>
            {
                new Photo
                {
                    Title = "Test Photo",
                    Description = "Your Description",
                    UserName = "NaokiSato",
                    PhotoFile = getFileBytes("\\Images\\flower.jpg"),
                    ImageMimeType ="image / jpeg",
                    CreatedDate = DateTime.Today
            }
        };
            photos.ForEach(s => context.Photos.Add(s));
            context.SaveChanges();
            var comments = new List<Comment>
            {
                new Comment
                {
                    PhotoID=1,
                    UserName="NaokiSato",
                    Subject="Test Comment",
                    Body="This comment" + "should appear in" + "Photo 1"
                }
            };

            comments.ForEach(s => context.Comments.Add(s));
            context.SaveChanges();
        }

    }
}

PhotoSharingApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoSharingApplication.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PhotoSharingApplication/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Globalization;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{
    [HandleError(View = "Error")]
    [ValueReporter]
    public class PhotoController : Controller
    {
        private PhotoSharingContext context = new PhotoSharingContext();

        //
        // GET: /Photo/

        public ActionResult Index()
        {
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Photo> photos;
            if (number == 0)
            {
                photos = context.Photos.ToList();
            }
            else
            {
                photos = (
                from p in context.Photos
                orderby p.CreatedDate descending
select p).Take(number).ToList();
            }
            return PartialView("_PhotoGallery", photos);

        }

        public ActionResult Display(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);
        }

        public ActionResult Create()
        {
            Photo newPhoto = new Photo();
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        [HttpPost]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.CreatedDate = DateTime.Today;
            if (!ModelState.IsValid)
            {
                return View("Create", photo);
            }
            else
            {
                if (image != null)
                {
                    photo.ImageMimeType = image.ContentType;
                    photo.PhotoFile = new byte[image.ContentLength];
                    image.InputStream.Read(photo.PhotoFile, 0, image.ContentLength);
                }
                context.Photos.Add(photo);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Delete", photo);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = context.Photos.Find(id);
            context.Photos.Remove(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileContentResult GetImage(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo != null)
            {
                return File(photo.PhotoFile, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult SlideShow()
        {
            throw new NotImplementedException("The Slideshow action is not yet ready.");
        }
    }
}

PhotoSharingApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome to Adventure Works Photo Sharing";
}

        <p>
            Welcome to Adventure Works Photo
            sharing! Use this site to share
            your adventures.
        </p>
        <h2>Latest Photos</h2>
        @Html.Action("_PhotoGallery", "Photo", new { number = 3 })

PhotoSharingApplication/Views/Photo/Create.cshtml
@model PhotoSharingApplication.Models.Photo

@{
    ViewBag.Title = "Create New Photo";
}

<h2>Create New Photo</h2>
@using (Html.BeginForm("Create", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.Title):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </span>
    </div>
    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.PhotoFile)
        </span>
        <span class="editor-field">
            <input type="file" name="Image" />
        </span>
    </div>

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.Description):
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </span>
    </div>

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.UserName):
        </span>
        <span class="editor-field">
            @Html.DisplayFor(model => model.UserName)
        </span>
    </div>

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.CreatedDate):
        </span>
        <span class="editor-field">
            @Html.DisplayFor(model => model.CreatedDate)
        </span>
    </div>

    <p>
        <input type="submit" value="Create" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PhotoSharingApplication/Views/Photo/Delete.cshtml
@model PhotoSharingApplication.Models.Photo

@{
    ViewBag.Title = "Delete Photo: " + Model.Title;
}

<h2>Delete Photo: "@Model.Title"</h2>

<p>Are you sure you want to delete this photo?</p>

@using (Html.BeginForm("Delete", "Photo", FormMethod.Post))
{
    <div class="photo-display">
        <img width="200" src="@Url.Action("GetImage", "Photo", new { id = Model.PhotoID })" />
    </div>

    <div class="photo-description">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="photo-metadata">
        <div>
            <span class="display-label">
                @Html.DisplayNameFor(model => model.UserName):
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => model.UserName)
            </span>
        </div>

        <div>
            <span class="display-label">
                @Html.DisplayNameFor(model => model.CreatedDate):
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => model.CreatedDate)
            </span>
        </div>
    </div>

    <p>
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PhotoSharingApplication/Views/Photo/Display.cshtml
@model PhotoSharingApplication.Models.Photo

@{
    ViewBag.Title = Model.Title;
}

<h2>"@Model.Title"</h2>

@if (Model.PhotoFile != null)
{
    <div class="photo-display">
        <img width="800" src="@Url.Action("GetImage", "Photo", new { id = Model.PhotoID })" />
    </div>
}

<div class="photo-description">
    @Html.DisplayFor(model => model.Description)
</div>

<div class="photo-metadata">

    <div>
        <span class="display-label">
            @Html.DisplayNameFor(model => model.UserName):
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.UserName)
        </span>
    </div>

    <div>
        <span class="display-label">
            @Html.DisplayNameFor(model => model.CreatedDate):
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.CreatedDate)
        </span>
    </div>

</div>

<p>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Delete This Photo", "Delete", new { id = Model.PhotoID })
</p>

PhotoSharingApplication/Views/Photo/Index.cshtml
@{
    ViewBag.Title = "All Photos";
}

<h2>All Photos</h2>

@Html.Action("_PhotoGallery", "Photo")

PhotoSharingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

PhotoSharingApplication/Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/PhotoSharingStyles.css" rel="stylesheet" />
</head>
<body>
    <div>
        <h1 class="site-page-title">
            Adventure Works Photo Sharing
        </h1>
        <div class="clear-floats" />
        <div id="topmenu">
            <nav>
                <ul >
                    <li class="topmenulink"><a  href="#">Inicio</a></li>
                    <li class="topmenulink"><a href="#">Quiénes somos</a></li>
                    <li class="topmenulink"><a href="#">Servicios</a></li>
                    <li class="topmenulink"><a href="#">Blog</a></li>
                    <li class="topmenulink"><a href="#">Contacto</a></li>
                </ul>
            </nav>
        </div>
        <div id="breadcrumb">
            Zona de mapa del sitio
        </div>
        <div>
            @RenderBody()
        </div>

    </div>
</body>
</html>

PhotoSharingApplication/Views/Shared/_PhotoGallery.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

@foreach (var item in Model)
{
    <div class="photo-index-card">
        <h3>"@item.Title"</h3>
       @if (item.PhotoFile != null)
        {
        <img class="photo-index-card-img" src="@Url.Action("GetImage", "Photo", new { id = item.PhotoID })" />
        }
        <div class="photo-metadata">


            <p class="display-field">
                Created By:
                @Html.DisplayFor(
                model => item.UserName)
            </p>
            <p class="display-label">
                Created On:
                @Html.DisplayFor(
                model => item.CreatedDate)
            </p>
            @Html.ActionLink("Display", "Display", new { id = item.PhotoID })
        </div>
        </div>
        }